language: python
python:
- '3.8'
install:
- python setup.py install
- pip install mypy git+https://github.com/numpy/numpy-stubs
script:
- python -m pytest --pspec tests/
- mypy
deploy:
  provider: pypi
  user: ritchie46
  password:
    secure: h8Ox4+ZF4QWLqHcdjKs47oPFJqmkPH0AYTGRyUT7wzAStF2cz/DMopLWKCOCd+/KfYy/9ULp8Ew/LOey7kLP5V0epbpEOgXP0O1sVk8JYo9Vt7J09DfEDIJcNw0l6XJq9jjK3yNvE59ekLDgVR3dU6o9btmaXS2tqUfuzvlkDRoR+N2yHCdA23oi6RLnnqi5DEJtpzf++b9eNNFPwbfBQqqmyw/wuoIENJ2O6JIL1Hz+uCag8n4+xQnyJERUIGS1xamjPdklP9tku824xirPOizJPE7LP5hb6uqohhEzdT5Oi/hizMP4Tt35vzMTpFiJygRmKgZuQz65aSUDSmInahearjPBmNkvtMMqrJ6fFWPEqbpvRJO2QkbwEBpwl3kfKiV4te/N0e44KkmQviyyf4Piy3W0wdE/MuBzEldg0p47V8DPokpTN+nvR4BLyrh8xq002KpkB5H+t9uVmwyFmKcZuqXnIZjlNv1bhZ2jN9qLOvOG2zP7Ju6AbmPDWzW4ryQPCc0VsTm5Mk9NUwJhU2z7rrJnwV0HORIgv2WBc7SgAkuT8xmKF95+sK67CEyitJHo/KOcVhg0ohamK2i0iifH1BkXFxc+V3mbkwvCM7zCa+F4KNKH4PuNEDi5jMQ7XuHM+Y2MhVGupHdtCfhM/C1ecJ2en2LDJwG2vk5q+ks=
  on:
    branch: release
  skip_existing: true
  distributions: "sdist bdist_wheel"
